# Site Settings
url: https://wangjiaqi-clinic.github.io
title: Jiaqi Wang's Homepage
description: "Jiaqi Wang's Homepage"
keywords: 王嘉淇, Jiaqi Wang
timezone: Asia/Shanghai
encoding: "utf-8"
SEOTitle: Jiaqi Wang's Homepage
repository: wangjiaqi-clinic/wangjiaqi-clinic.github.io

# Author Settings
author: Jiaqi Wang
github_username: wangjiaqi-clinic
location: Wuhan, China
email: jiaqiwangclinic@gmail.com

# RSS Settings
RSS: true
subscribe_rss: /feed.xml

# Build Settings
highlighter: rouge
paginate: 10
permalink: pretty
gems: [jekyll-paginate]
collections:
    wiki:
        output: true
        permalink: /wiki/:path/
        
# Markdown Settings
markdown: kramdown
kramdown:
    input: GFM
mathjax: true

