# Site Settings
url: https://wangjiaqi-clinic.github.io
title: Peiqin Lin's Homepage
subtitle: "Software is like sex: it's better when it's free."
description: "Peiqin Lin's Homepage"
keywords: 林佩勤, Peiqin Lin, 半截小丑, lpq29743
timezone: Asia/Shanghai
encoding: "utf-8"
SEOTitle: Peiqin Lin's Homepage
repository: wangjiaqi-clinic/wangjiaqi-clinic.github.io

# Author Settings
author: Peiqin Lin
github_username: Wang-jiaqi
location: Guangdong, China
email: lpq29743@gmail.com

# Navigation Settings
navs:
  -
    href: 
    label: Home

# RSS Settings
RSS: true
subscribe_rss: /feed.xml

# Build Settings
highlighter: rouge
paginate: 10
permalink: pretty
gems: [jekyll-paginate]
collections:
    wiki:
        output: true
        permalink: /wiki/:path/
        
# Markdown Settings
markdown: kramdown
kramdown:
    input: GFM
mathjax: true

